### ISSUE TITLE
Upgrade boto to boto3 to resolve 

### ISSUE THREAD

**Issue by rufuspollock** [datahq/bitstore#9]
We're getting internal server errors on bitstore. Issue is that our boto lib does not support buckets with '.' in them (see below)

This is a bug in boto - https://github.com/boto/boto/issues/2836. Fixed in boto3 so i'm going to try and upgrade. (This also bit opentrials folks https://github.com/opentrials/opentrials-airflow/commit/72b4848660a2996c2cc7f30d379fdeb63915f7f2)

```
[rawstore-1]2017-07-11T17:07:33.867500137Z [2017-07-11 17:07:33 +0000] [10] [INFO] Booting worker with pid: 10
[rawstore-1]2017-07-11T17:16:30.249768731Z [2017-07-11 17:16:30,240] ERROR in app: Exception on /rawstore/authorize [POST]
[rawstore-1]2017-07-11T17:16:30.249912369Z Traceback (most recent call last):
[rawstore-1]2017-07-11T17:16:30.249922041Z   File "/usr/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
[rawstore-1]2017-07-11T17:16:30.249927893Z     response = self.full_dispatch_request()
[rawstore-1]2017-07-11T17:16:30.249933298Z   File "/usr/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
[rawstore-1]2017-07-11T17:16:30.249938794Z     rv = self.handle_user_exception(e)
[rawstore-1]2017-07-11T17:16:30.249954976Z   File "/usr/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
[rawstore-1]2017-07-11T17:16:30.249961831Z     return cors_after_request(app.make_response(f(*args, **kwargs)))
[rawstore-1]2017-07-11T17:16:30.249967128Z   File "/usr/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
[rawstore-1]2017-07-11T17:16:30.249972434Z     reraise(exc_type, exc_value, tb)
[rawstore-1]2017-07-11T17:16:30.249977399Z   File "/usr/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
[rawstore-1]2017-07-11T17:16:30.249983279Z     raise value
[rawstore-1]2017-07-11T17:16:30.249992271Z   File "/usr/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
[rawstore-1]2017-07-11T17:16:30.249997564Z     rv = self.dispatch_request()
[rawstore-1]2017-07-11T17:16:30.250002638Z   File "/usr/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
[rawstore-1]2017-07-11T17:16:30.250011846Z     return self.view_functions[rule.endpoint](**req.view_args)
[rawstore-1]2017-07-11T17:16:30.250017448Z   File "/opt/app/bitstore/blueprint.py", line 19, in authorize
[rawstore-1]2017-07-11T17:16:30.250022699Z     return controllers.authorize(controllers.S3Connection(),
[rawstore-1]2017-07-11T17:16:30.250027783Z   File "/opt/app/bitstore/controllers.py", line 25, in __init__
[rawstore-1]2017-07-11T17:16:30.250033013Z     config['STORAGE_BUCKET_NAME'])
[rawstore-1]2017-07-11T17:16:30.250037913Z   File "/usr/lib/python3.6/site-packages/boto/s3/connection.py", line 509, in get_bucket
[rawstore-1]2017-07-11T17:16:30.250043078Z     return self.head_bucket(bucket_name, headers=headers)
[rawstore-1]2017-07-11T17:16:30.250048089Z   File "/usr/lib/python3.6/site-packages/boto/s3/connection.py", line 528, in head_bucket
[rawstore-1]2017-07-11T17:16:30.250053133Z     response = self.make_request('HEAD', bucket_name, headers=headers)
[rawstore-1]2017-07-11T17:16:30.250058053Z   File "/usr/lib/python3.6/site-packages/boto/s3/connection.py", line 671, in make_request
[rawstore-1]2017-07-11T17:16:30.250063159Z     retry_handler=retry_handler
[rawstore-1]2017-07-11T17:16:30.250067998Z   File "/usr/lib/python3.6/site-packages/boto/connection.py", line 1071, in make_request
[rawstore-1]2017-07-11T17:16:30.250111953Z     retry_handler=retry_handler)
[rawstore-1]2017-07-11T17:16:30.250117769Z   File "/usr/lib/python3.6/site-packages/boto/connection.py", line 943, in _mexe
[rawstore-1]2017-07-11T17:16:30.250122480Z     request.body, request.headers)
[rawstore-1]2017-07-11T17:16:30.250127000Z   File "/usr/lib/python3.6/http/client.py", line 1239, in request
[rawstore-1]2017-07-11T17:16:30.250131621Z     self._send_request(method, url, body, headers, encode_chunked)
[rawstore-1]2017-07-11T17:16:30.250136163Z   File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
[rawstore-1]2017-07-11T17:16:30.250140643Z     self.endheaders(body, encode_chunked=encode_chunked)
[rawstore-1]2017-07-11T17:16:30.250145173Z   File "/usr/lib/python3.6/
```

**Comment by rufuspollock** [comment]
Reopening as missed out stuff in the port: adding the conditions for S3.

Note this is a bit confusing in boto docs as Conditions are not explained in the boto3 docs: http://boto3.readthedocs.io/en/latest/guide/s3.html#generating-presigned-posts

However some digging in the source revealed core of this in botocore which has better docs:

http://botocore.readthedocs.io/en/latest/reference/services/s3.html#S3.Client.generate_presigned_post

Makes me wonder if we should just use botocore!

**Comment by rufuspollock** [comment]
FIXED.
